[package]
name = "ophidiedev/minstance"
description = "A very fast Instance serializer for Roblox that can serialize 40,000 Instances and compress it into a 100K+ character string in only 0.4s"
authors = ["Ophidie","kieldbg"]
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/OphidieDev/MInstance"

[dependencies]
